import Comments from '@/app/components/Comments';
import getAllPosts from '@/lib/getAllPosts';
import getPost from '@/lib/getPost';
import getPostComments from '@/lib/getPostComments';
import { Suspense } from 'react'

export const metadata = {
  title: "Single Post - Next App",
  description: "Generated by create next app",
}

export default async function PostPage({ params }) {
  // console.log('In Single Post', params.id);
  const { id } = params;
  const postPromise = getPost(id);

  const commentsPromise = getPostComments(id);

  const post = await postPromise;

  return (
    <div>
      <h3 className='font-semibold text-xl my-5'>
        {post.title}
      </h3>
      <p>
        {post.body}
      </p>
      <Suspense fallback='Loading Comments...'>
        <Comments
          promise={commentsPromise}
        />
      </Suspense>
    </div>
  )
}

// SSG (Static Site Generation)
export async function generateStaticParams() {
  const posts = await getAllPosts();
  // next js De-Duplicate these function invocations
  /*
  return
    [
      {id: 1},
      {id: 2},
      {id: 3},
      ... ... ...
      {id: 10},
    ]
  */
  return posts?.map(post => ({
    id: post.id.toString()
  }))
  /* return posts?.map(post => {
    return {
      id: post.id.toString()
    }
  }) */
}